# Generated by Django 3.1.4 on 2022-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
