# Generated by Django 3.1.4 on 2022-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20220307_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(to='item.Group')),
            ],
        ),
    ]
