# Generated by Django 3.1.4 on 2022-03-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_itemnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemnew',
            name='groups',
        ),
        migrations.AddField(
            model_name='item',
            name='groups',
            field=models.ManyToManyField(to='item.Group'),
        ),
        migrations.DeleteModel(
            name='ItemGroup',
        ),
        migrations.DeleteModel(
            name='ItemNew',
        ),
    ]
