# Generated by Django 3.1.4 on 2022-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20220327_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
